name: "Deploy Akamai Image Manager Policy"
description: "Github Actions to deploy Akamai Image Manager Policies"
author: Achuthananda
inputs:
  setPolicy:
    description:  'Name of Set Policy'
    required: true
  policyName:
    description:  'Name of Policy'
    required: true
  network:
    description:  'Network to deploy the policy[staging/production/both]'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.setPolicy}}
    - ${{ inputs.policyName}}
    - ${{ inputs.network}}
branding:
  color: orange
  icon: cloud-lightning
